2.11 Write Python expressions corresponding to these statements:

(a) The sum of negative integers −7 through −1

(b) The average age of a group of kids at a summer camp given than 17 are 9 years old,24 are 10 years old, 21 are 11 years old, and 27 are 12 years old

(c) 2 to the power −20

(d) The number of times 61 goes into 4356

(e) The remainder when 4365 is divided by 61

In [4]:
#a
-7-6-5-4-3-2-1

-28

In [15]:
#b
(17*9+24*10+21*11+27*12)/(17+24+21+27)

10.651685393258427

In [16]:
#c
2**-20

9.5367431640625e-07

In [17]:
#d
4356//61

71

In [18]:
#e
4365%61

34

2.12 Start by evaluating, in the interactive shell, the assignment:

s1 = '-',s2 = '+'

Now write string expressions involving s1 and s2 and string operators + and * that evaluate
to:

(a) '-+'

(b) '-+-'

(c) '+––'

(d) '+– –+– –'

(e) '+– –+– –+– –+– –+– –+– –+– –+– –+– –+– –+'

(f) '+–+++– –+–+++– –+–+++– –+–+++– –+–+++– –'

Try to make your string expressions as succinct as you can.

In [19]:
s1='-'
s2='+'

In [20]:
#a
s1+s2

'-+'

In [21]:
#b
s1+s2+s1

'-+-'

In [22]:
#c
s2+s1+s1

'+--'

In [23]:
#d
(s2+s1+s1)*2

'+--+--'

In [25]:
#e
(s2+s1+s1)*10+s2

'+--+--+--+--+--+--+--+--+--+--+'

In [26]:
#f
5*(s2+s1+s2+s2+s2+s1+s1)

'+-+++--+-+++--+-+++--+-+++--+-+++--'

2.13 Start by running, in the shell, the following assignment statement:

s = 'abcdefghijklmnopqrstuvwxyz'

Now write expressions using string s and the indexing operator that evaluate to 'a', 'c',
'z', 'y', and 'q'.

In [27]:
s = 'abcdefghijklmnopqrstuvwxyz'

In [28]:
s[0]


'a'

In [29]:
s[2]

'c'

In [30]:
s[-1]

'z'

In [31]:
s[-2]

'y'

In [33]:
s[16]

'q'

2.14 Start by executing

s = 'goodbye'

Then write a Boolean expression that checks whether:

(a) The first character of string s is 'g'

(b) The seventh character of s is 'g'

(c) The first two characters of s are 'g' and 'a'

(d) The next to last character of s is 'x'

(e) The middle character of s is 'd'

(f) The first and last characters of string s are equal

(g) The last four characters of string s match the string 'tion'

Note: These seven statements should evaluate to True, False, False, False, True, False,
and False, respectively

In [36]:
s = 'goodbye'

In [37]:
s[0]=='g'

True

In [38]:
s[6]=='g'

False

In [39]:
s[0]=='g' and s[1]=='a'

False

In [40]:
s[-2]=='x'

False

In [45]:
a= len(s)//2
s[a]=='d'

True

In [46]:
s[1]==s[-1]

False

In [49]:
s[-4:]=="tion"

False

2.15 Write Python expressions corresponding to these statements:

(a) The number of characters in the word "anachronistically" is 1 more than the number
of characters in the word "counterintuitive."

(b) The word "misinterpretation" appears earlier in the dictionary than the word "misrepresentation."

(c) The letter "e" does not appear in the word "floccinaucinihilipilification."

(d) The number of characters in the word "counterrevolution" is equal to the sum of the
number of characters in words "counter" and "resolution."


In [51]:
len("anachronistically")==len("counterintuitive")+1

True

In [52]:
"misinterpretation"<"misrepresentation"

True

In [1]:
'e'not in  "floccinaucinihilipilification"

True

In [54]:
len("counterrevolution")== len( "counter")+len("resolution")

True

2.16 Write the corresponding Python assignment statements:

(a) Assign 6 to variable a and 7 to variable b.

(b) Assign to variable c the average of variables a and b.

(c) Assign to variable inventory the list containing strings 'paper', 'staples', and
'pencils'.

(d) Assign to variables first, middle and last the strings 'John', 'Fitzgerald',
and 'Kennedy'.

(e) Assign to variable fullname the concatenation of string variables first, middle,
and last. Make sure you incorporate blank spaces appropriately.

In [56]:
a=6
b=7

In [58]:
c=(a+b)/2
c

6.5

In [59]:
inventory= ['papers','staples', 'pencils']

In [66]:
first, middle, last='John', 'Fitzgerald', 'Kennedy'

In [67]:
fullname= first+" "+middle+" "+last
fullname

'John Fitzgerald Kennedy'

2.17 Using variables defined in Exercise 2.16, write Boolean expressions corresponding to
the following logical statements and evaluate the expressions:

(a) The sum of 17 and −9 is less than 10.

(b) The length of list inventory is more than five times the length of string fullname.

(c) c is no more than 24.

(d) 6.75 is between the values of integers a and b.

(e) The length of string middle is larger than the length of string first and smaller than
the length string last.

(f) Either the list inventory is empty or it has more than 10 objects in it.

In [68]:
17+-9<10

True

In [71]:
len(inventory)> 5*len(fullname)

False

In [72]:
c<24

True

In [73]:
a<6.75<b

True

In [74]:
len(middle)>len(first) and len(middle)<len(last)

False

In [75]:
len(inventory)==0 or len(inventory)>10

False

2.18 Write Python statements corresponding to the following:

(a) Assign to variable flowers a list containing strings 'rose', 'bougainvillea',
'yucca', 'marigold', 'daylilly', and 'lilly of the valley'.

(b) Write a Boolean expression that evaluates to True if string 'potato' is in list flowers,
and evaluate the expression.

(c) Assign to list thorny the sublist consisting of the first three objects in list flowers.

(d) Assign to list poisonous the sublist consisting of just the last object of list flowers.

(e) Assign to list dangerous the concatenation of lists thorny and poisonous.


In [6]:
flowers=[ 'rose','bougainvillea','yucca','marigold','daylilly','lilly of the valley']

In [7]:
'potato'in flowers

False

In [8]:
thorny=flowers[0:3]
thorny

['rose', 'bougainvillea', 'yucca']

In [13]:
s=flowers[::2]
s

['rose', 'yucca', 'daylilly']

In [24]:
poisonous=flowers[-1]
poisonous

'lilly of the valley'

In [26]:
list(poisonous.split("\n"))

['lilly of the valley']

In [27]:
dangerous= thorny+list(poisonous.split("  "))
dangerous

['rose', 'bougainvillea', 'yucca', 'lilly of the valley']

2.19 Start by assigning to variable answers a list containing an arbitrary sequence of strings
'Y' and 'N'. For example:
answers = [ 'Y', 'N', 'N','Y', 'N', 'Y', 'Y', 'Y', 'N', 'N', 'N']

Write Python statements corresponding to the following:

(a) Assign to variable numYes the number of occurrences of 'Y' in list answers.

(b) Assign to variable numNo the number of occurrences of 'N' in list answers.

(c) Assign to variable percentYes the percentage of strings in answers that are 'Y'.

(d) Sort the list answers.

(e) Assign to variable f the index of the first occurrence of 'Y' in sorted list answers.

In [28]:
answers= ["Y","N","N","Y","N","Y","Y","Y","N","N","N"]

In [29]:
numYes= answers.count('Y')
numYes

5

In [30]:
numNo= answers.count('N')
numNo

6

In [31]:
percentYes= numYes/len(answers)*100
percentYes

45.45454545454545

In [28]:
answers.sort()

In [29]:
f=answers.index('Y')
f

6

2.20 Write an expression involving a three-letter string s that evaluates to a string whose
characters are the characters of s in reverse order. If s is 'top', the expression should
evaluate to 'pot'.

In [126]:
s="top"


In [129]:
r=s[::-1]
r

'pot'

2.21 Write an expression involving strings s and t containing the last name and the first
name, respectively, of a person that evaluates to the person’s initials. If the two strings contained the first and last name of this book’s author, the expression would evaluate to 'LP'.

In [130]:
t="Ljubomir"
s="Perkovic"

In [132]:
result= t[0]+s[0]
result

'LP'

2.22 The range of a list of numbers is the largest difference between any two numbers in the
list. Write a Python expression that computes the range of a list of numbers lst. If the list
lst is, say, [3, 7, -2, 12], the expression should evaluate to 14 (the difference between
12 and −2).


In [134]:
lst= [3, 7, -2, 12]

In [135]:
range_lst=max(lst)-min(lst)
range_lst

14

2.23 Start by assigning to variables monthsL and monthsT a list and a tuple, respectively,
both containing strings 'Jan', 'Feb', 'Mar', and 'May', in that order. Then attempt the
following with both containers:

(a) Insert string 'Apr' between 'Mar' and 'May'.

(b) Append string 'Jun'.

(c) Pop the container.

(d) Remove the second item in the container.

(e) Reverse the order of items in the container.

(f) Sort the container.


In [30]:
monthsL=[ 'Jan', 'Feb', 'Mar','May']
monthsT=( 'Jan', 'Feb', 'Mar','May')

In [31]:
monthsL.insert(3,'Apr')
monthsL

['Jan', 'Feb', 'Mar', 'Apr', 'May']

In [32]:
monthsT.insert(3,'Apr')

AttributeError: 'tuple' object has no attribute 'insert'

In [33]:
monthsL.append('Jun')
monthsL

['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun']

In [34]:
monthsT.append('Jun')

AttributeError: 'tuple' object has no attribute 'append'

In [35]:
monthsL.pop(1)
monthsL

['Jan', 'Mar', 'Apr', 'May', 'Jun']

In [36]:
monthsT.pop(1)

AttributeError: 'tuple' object has no attribute 'pop'

In [40]:
a=monthsL[1]

In [49]:
monthsL.remove(monthsL[1])

In [50]:
monthsL

['Jan', 'May', 'Jun']

In [51]:
monthsT.remove(monthsT[2])

AttributeError: 'tuple' object has no attribute 'remove'

In [52]:
monthsL.reverse()

In [53]:
monthsL

['Jun', 'May', 'Jan']

In [54]:
monthsT.reverse()

AttributeError: 'tuple' object has no attribute 'reverse'

In [55]:
 monthsL.sort()

In [56]:
monthsL

['Jan', 'Jun', 'May']

In [57]:
monthsT.sort()

AttributeError: 'tuple' object has no attribute 'sort'

2.24 Start by assigning to variable grades a list containing an arbitrary sequence of grades
(strings) 'A', 'B', 'C', 'D', and 'F'. For example:

grades = ['B','B','F','C','B','A','A','D','C','D','A','A','B']

Write a sequence of Python statements that ultimately produce a list count that contains
the numbers of occurrences of each grade in list grades in alphabetic order. For the given
example, the list count should be [4, 4, 2, 2, 1].


In [33]:
grades = ['B','B','F','C','B','A','A','D','C','D','A','A','B']

In [34]:
A= grades.count('A')
A

4

In [35]:
B= grades.count('B')

In [36]:
C= grades.count('C')

In [37]:
D= grades.count('D')

In [38]:
F=grades.count('F')

In [39]:
lst_count= [A,B,C,D,F]

In [40]:
lst_count

[4, 4, 2, 2, 1]

In [47]:
s=set(grades)
l=list(s)
l.sort()
c=[]
for i in range(0,len(l)):
    c.append(grades.count(l[i]))
c    

[4, 4, 2, 2, 1]

2.25 Repeat Problem 2.24 with the following modification: variable grades is defined to
be of type tuple rather than of type list:

grades = ('B','B','F','C','B','A','A','D','C','D','A','A','B')

Variable count should still refer to a list.


In [46]:
grades = ('B','B','F','C','B','A','A','D','C','D','A','A','B')

In [180]:
a= grades.count('A')

In [181]:
b= grades.count('B')

In [182]:
c= grades.count('C')

In [183]:
d= grades.count('D')

In [184]:
f=grades.count('F')

In [185]:
lst_count= [a,b,c,d,f]

In [186]:
lst_count

[4, 4, 2, 2, 1]

2.26 A dartboard of radius 10 and the wall it is hanging on are represented using the twodimensional coordinate system, with the board’s center at coordinate (0, 0). Variables x and
y store the x- and y-coordinate of a dart hit. Write an expression using variables x and y
that evaluates to True if the dart hits (is within) the dartboard, and evaluate the expression
for these dart coordinates:

(a) (0, 0)

(b) (10, 10)

(c) (6, −6)

(d) (−7, 8)

In [187]:
x1=0
y1=0
x1**2+y1**2<10**2

True

In [188]:
x2=10
y2=10
x2**2+y2**2<10**2

False

In [189]:
x3=6
y3=-6
x3**2+y3**2<10**2

True

In [190]:
x4=-7
y4=8
x4**2+y4**2<10**2

False

2.27 A ladder put up right against a wall will fall over unless put up at a certain angle less
than 90 degrees. Given variables length and angle storing the length of the ladder and the
angle that it forms with the ground as it leans against the wall, write a Python expression
involving length and angle that computes the height reached by the ladder. Evaluate the
expression for these values of length and angle:

(a) 16 feet and 75 degrees

(b) 20 feet and 0 degrees

(c) 24 feet and 45 degrees

(d) 24 feet and 80 degrees

Note: You will need to use the trig formula:

height = length ∗ sin(angle)

The math module sin() function takes its input in radians. You will thus need to convert
the angle given in degrees to the angle given in radians using:

radians =(π ∗ degrees)/180


In [194]:
l1=16
a1=75
import math
a1_rad=(math.pi*a1)/180
height1= l1* math.sin(a1_rad)
height1


15.454813220625093

In [195]:
l2=20
a2=0
a2_rad=(math.pi*a2)/180
height2= l2* math.sin(a2_rad)
height2

0.0

In [196]:
l3=24
a3=45
a3_rad=(math.pi*a3)/180
height3= l3* math.sin(a3_rad)
height3

16.970562748477143

In [197]:
l4=24
a4=80
a4_rad=(math.pi*a4)/180
height4= l4* math.sin(a4_rad)
height4

23.63538607229299

2.28 Write the relevant Python expression or statement, involving a list of numbers lst
and using list operators and methods for these specifications:

(a) An expression that evaluates to the index of the middle element of lst

(b) An expression that evaluates to the middle element of lst

(c) A statement that sorts the list lst in descending order

(d) A statement that removes the first number of list lst and puts it at the end

Note: If a list has even length, then the middle element is defined to be the rightmost of the
two elements in the middle of the list.

In [62]:
lst=[2,4,5,7,8,3,6,1,9]
middle_index=len(lst)//2
middle_index

4

In [63]:
lst[middle_index]

8

In [65]:
lst.sort(reverse=True)

In [212]:
lst.reverse()

In [67]:
num=lst.pop(0)

In [68]:
lst.append(num)

In [69]:
lst

[8, 7, 6, 5, 4, 3, 2, 1, 9]

2.29 Add one or more pairs of parentheses to each expression so that it evaluates to True.

(a) 0 == 1 == 2

(b) 2 + 3 == 4 + 5 == 7

(c) 1 < -1 == 3 > 4

For each expression, explain in what order the operators were evaluated.

In [71]:
0 ==(1 == 2)

False

In [236]:
(2 + (3 == 4) + 5) == 7

True

In [238]:
(1 < -1) == (3 > 4)

True

2.30 Using an example of your own, explicitly convert some string to a list. Describe, in
your own words, the behavior of the list constructor on a string input.

In [239]:
str1= "Old is Gold"
lst= list(str1.split(" "))
lst

['Old', 'is', 'Gold']

In [57]:
year=int(input())
leap=True
if year%400==0 :
    leap = True
elif year%4 == 0 and year%100 != 0:
    leap = True
else:
    leap=False
leap

2020


True

In [59]:
mark=int(input())
if(mark>90):
    print("a")
elif(mark>80):
    print("b")
elif(mark>70):
    print("c")
else:
    print("f")

76
c


In [62]:
d={1:"archana",2:"sandra",3:"aparna",4:"avani"}
d.get(1,10)

'archana'

In [63]:
d.values()

dict_values(['archana', 'sandra', 'aparna', 'avani'])

In [64]:
d.items()

dict_items([(1, 'archana'), (2, 'sandra'), (3, 'aparna'), (4, 'avani')])

In [65]:
d.keys()

dict_keys([1, 2, 3, 4])

In [66]:
d1={1:10,5:30}
d.update(d1)

In [67]:
d


{1: 10, 2: 'sandra', 3: 'aparna', 4: 'avani', 5: 30}

In [68]:
d.pop(1)

10

In [71]:
l=[1,2,3,4,5]
l1=[(4,5),{1:2}]
l.extend(l1)

In [72]:
l


[1, 2, 3, 4, 5, (4, 5), {1: 2}]

In [77]:
n=int(input())
for i in range(1,11):
    m=i*n
    print("{}*{} ={}".format(i,n,m))

5
1*5 =5
2*5 =10
3*5 =15
4*5 =20
5*5 =25
6*5 =30
7*5 =35
8*5 =40
9*5 =45
10*5 =50


In [81]:
infile=open("example.txt",'r')
txt=infile.read()
txt

'Hello WorldWelcome to Futures'

In [21]:
outfile=open("example.txt",'w')
outfile.write("Welcome")
infile=open("example.txt",'a')
infile.write("abcdefg")
infile1=open("example.txt",'w+')
infile1.write("hello")
txt=infile1.read()
txt

''

In [24]:
infile1=open("example.txt",'r')
txt=infile1.read()
txt
infile.close()

In [20]:
import numpy as np
A=np.array([[8,3,-2],[-4,7,5],[3,4,-12]])
b=np.array([9,15,35])
x=np.linalg.solve(A,b)
x

array([-0.58226371,  3.22870478, -1.98599767])

In [2]:
import numpy as np

A = np.array([[8, 3, -2], [-4, 7, 5], [3, 4, -12]])
b = np.array([9, 15, 35])
x = np.linalg.solve(A, b)
x

array([-0.58226371,  3.22870478, -1.98599767])

In [3]:
import random
n=random.randint(1,100)
i=int(input())
print(n) 
l=1
while(i!=n):
    if(i<n):
        print("smaller")
    else:
        print("bigger")
    l+=1   
    i=int(input())
print("Excellent")
print(l)

ValueError: invalid literal for int() with base 10: ''

In [4]:
n=int(input())
s=str(n)
s=s[::-1]
n1=int(s)
if(n==n1):
    print("palindrome")
else:
    print("not palindrome")

ValueError: invalid literal for int() with base 10: ''

In [5]:
n=np.array([[2,3,4],[4,5,6]])

In [6]:
n=np.append(n,[[5,6,7]],axis=0)

In [7]:
n

array([[2, 3, 4],
       [4, 5, 6],
       [5, 6, 7]])

In [8]:
np.delete(n,1,axis=0)

array([[2, 3, 4],
       [5, 6, 7]])

In [9]:
n

array([[2, 3, 4],
       [4, 5, 6],
       [5, 6, 7]])

In [10]:
a = np.array([[1, 1], [2, 2], [3, 3]])
a
array([[1, 1],
       [2, 2],
       [3, 3]])
np.insert(a, 1, 5)
array([1, 5, 1, ..., 2, 3, 3])
np.insert(a, 1, 5, axis=1)
array([[1, 5, 1],
       [2, 5, 2],
       [3, 5, 3]])

NameError: name 'array' is not defined

In [11]:
s="sandra loves joanne"
np.char.replace(s,"s","a")


array('aandra lovea joanne', dtype='<U19')

In [12]:
np.char.add("joanne","flcnd")

array('joanneflcnd', dtype='<U11')

In [13]:
np_array=np.array([1,2,3,4,5])

In [34]:
arr=np.array([[10,6],[2,7]])

In [35]:
np.linalg.det(arr)

58.000000000000036

In [36]:
np.linalg.inv(arr)

array([[ 0.12068966, -0.10344828],
       [-0.03448276,  0.17241379]])